"use client";

import MarketPageTemplate, { type MarketData } from "@/components/markets/MarketPageTemplate";

const data: MarketData = {
  name: "Acciones",
  tag: "EQUITIES",
  iconName: "briefcase",
  accentColor: "#C8A96A",
  accentRgb: "200,169,106",
  description:
    "111 CFDs de acciones en EE.UU., Europa y Asia. Opera las empresas líderes del mundo con ejecución institucional — de Apple y Tesla a Toyota y Tencent.",
  conditions: [
    { label: "Comisión EE.UU.",     raw: "0.006%",        std: "0.001%" },
    { label: "Comisión Europa",     raw: "0.0025%",       std: "0.0025%" },
    { label: "Comisión Asia",       raw: "0.003%",        std: "0.003%" },
    { label: "Apalancamiento máx.", raw: "1:20",          std: "1:20" },
    { label: "Modelo de ejecución", raw: "Book A · NDD",  std: "Book A · NDD" },
  ],
  groups: [
    {
      label: "EE.UU. — 41 acciones",
      instruments: [
        { symbol: "AAL",   name: "American Airlines" },
        { symbol: "AAPL",  name: "Apple" },
        { symbol: "AIG",   name: "American International Group" },
        { symbol: "AMZN",  name: "Amazon" },
        { symbol: "BABA",  name: "Alibaba Group" },
        { symbol: "BAC",   name: "Bank of America" },
        { symbol: "CSCO",  name: "Cisco Systems" },
        { symbol: "CVX",   name: "Chevron Corporation" },
        { symbol: "DIS",   name: "Walt Disney" },
        { symbol: "META",  name: "Meta Platforms" },
        { symbol: "FDX",   name: "FedEx Corporation" },
        { symbol: "GOOGL", name: "Alphabet Class A" },
        { symbol: "HPQ",   name: "HP Inc" },
        { symbol: "IBM",   name: "IBM" },
        { symbol: "ING",   name: "ING Group" },
        { symbol: "INTC",  name: "Intel" },
        { symbol: "JNJ",   name: "Johnson & Johnson" },
        { symbol: "JPM",   name: "JPMorgan Chase" },
        { symbol: "MAR",   name: "Marriott International" },
        { symbol: "MCD",   name: "McDonald's" },
        { symbol: "MMM",   name: "3M Company" },
        { symbol: "MRK",   name: "Merck & Co" },
        { symbol: "MSFT",  name: "Microsoft" },
        { symbol: "NDAQ",  name: "Nasdaq OMX Group" },
        { symbol: "NFLX",  name: "Netflix" },
        { symbol: "NKE",   name: "Nike" },
        { symbol: "ORCL",  name: "Oracle" },
        { symbol: "PEP",   name: "PepsiCo" },
        { symbol: "TSLA",  name: "Tesla" },
        { symbol: "UAL",   name: "United Airlines" },
        { symbol: "UNH",   name: "UnitedHealth Group" },
        { symbol: "WFC",   name: "Wells Fargo" },
        { symbol: "WKHS",  name: "Workhorse Group" },
        { symbol: "WMT",   name: "Walmart" },
        { symbol: "XOM",   name: "ExxonMobil" },
        { symbol: "NVDA",  name: "Nvidia" },
        { symbol: "MAT",   name: "Mattel" },
        { symbol: "DLPN",  name: "Dolphin Entertainment" },
        { symbol: "PLBY",  name: "PLBY Group" },
        { symbol: "FNKO",  name: "Funko Inc" },
        { symbol: "NET",   name: "Cloudflare" },
      ],
    },
    {
      label: "Europa — 25 acciones",
      instruments: [
        { symbol: "ADS",   name: "Adidas" },
        { symbol: "AIR",   name: "Airbus Group" },
        { symbol: "ALV",   name: "Allianz" },
        { symbol: "BAS",   name: "BASF" },
        { symbol: "BATS",  name: "British American Tobacco" },
        { symbol: "BAYN",  name: "Bayer" },
        { symbol: "BMW",   name: "BMW" },
        { symbol: "BNP",   name: "BNP Paribas" },
        { symbol: "DGE",   name: "Diageo" },
        { symbol: "DTE",   name: "Deutsche Telekom" },
        { symbol: "GLEN",  name: "Glencore" },
        { symbol: "GSK",   name: "GlaxoSmithKline" },
        { symbol: "IBE",   name: "Iberdrola" },
        { symbol: "LHA",   name: "Lufthansa" },
        { symbol: "MBG",   name: "Mercedes-Benz Group" },
        { symbol: "NESN",  name: "Nestle" },
        { symbol: "NOVN",  name: "Novartis" },
        { symbol: "PAH3",  name: "Porsche Automobil Holding" },
        { symbol: "RIO",   name: "Rio Tinto" },
        { symbol: "SAP",   name: "SAP" },
        { symbol: "SHEL",  name: "Shell PLC" },
        { symbol: "SIE",   name: "Siemens" },
        { symbol: "ULVR",  name: "Unilever" },
        { symbol: "VOD",   name: "Vodafone Group" },
        { symbol: "VOW3",  name: "Volkswagen" },
      ],
    },
    {
      label: "Asia — 30 acciones",
      instruments: [
        { symbol: "Canon",        name: "Canon" },
        { symbol: "ChinaMobile",  name: "China Mobile" },
        { symbol: "CITIC",        name: "CITIC Securities" },
        { symbol: "CKHutchison",  name: "CK Hutchison Holdings" },
        { symbol: "CNOOC",        name: "CNOOC" },
        { symbol: "Henderson",    name: "Henderson Land" },
        { symbol: "HKBankChina",  name: "Bank of China" },
        { symbol: "Honda",        name: "Honda Motor Company" },
        { symbol: "HSBC",         name: "HSBC Holdings" },
        { symbol: "Ind&ComBank",  name: "Industrial and Commercial Bank of China" },
        { symbol: "JDCom",        name: "JD.com Inc" },
        { symbol: "JpnTobacco",   name: "Japan Tobacco" },
        { symbol: "KDDI",         name: "KDDI" },
        { symbol: "Keyence",      name: "Keyence" },
        { symbol: "Lenovo",       name: "Lenovo Group" },
        { symbol: "Makita",       name: "Makita" },
        { symbol: "MitsubisUFJ",  name: "Mitsubishi UFJ Financial Group" },
        { symbol: "Mitsui",       name: "Mitsui & Co" },
        { symbol: "Mizuho",       name: "Mizuho Financial Group" },
        { symbol: "Nissan",       name: "Nissan Motor" },
        { symbol: "PICC",         name: "PICC Property and Casualty" },
        { symbol: "Seven&I",      name: "Seven & i Holdings" },
        { symbol: "ShenhuaEnrg",  name: "China Shenhua Energy" },
        { symbol: "SHK",          name: "SHK Properties" },
        { symbol: "Softbank",     name: "SoftBank Group" },
        { symbol: "Sony",         name: "Sony" },
        { symbol: "Sumitomo",     name: "Sumitomo Corporation" },
        { symbol: "Tencent",      name: "Tencent Holdings" },
        { symbol: "Toyota",       name: "Toyota Motor" },
        { symbol: "Xiaomi",       name: "Xiaomi" },
      ],
    },
  ],
};

export default function EsEquitiesPage() {
  return <MarketPageTemplate data={data} />;
}
