"use client";

import MarketPageTemplate, { type MarketData } from "@/components/markets/MarketPageTemplate";

const data: MarketData = {
  name: "Forex",
  tag: "FX",
  iconName: "arrowupdown",
  accentColor: "#00BAB3",
  accentRgb: "0,186,179",
  description:
    "101 pares de divisas: mayores, menores y exóticos. Ejecución ECN/STP institucional con spreads RAW desde 0,0 pips y la mayor liquidez FX disponible.",
  conditions: [
    { label: "Spread desde",      raw: "0,0 pips",     std: "1,6 pips" },
    { label: "Comisión",          raw: "39 USD/M",      std: "Zero" },
    { label: "Apalancamiento máx.", raw: "1:200",       std: "1:200" },
    { label: "Modelo de ejecución", raw: "Book A · NDD", std: "Book A · NDD" },
  ],
  groups: [
    {
      label: "Mayores",
      instruments: [
        { symbol: "AUDUSD", name: "Australian Dollar vs US Dollar" },
        { symbol: "EURUSD", name: "Euro vs US Dollar" },
        { symbol: "GBPUSD", name: "Great Britain Pound vs US Dollar" },
        { symbol: "NZDUSD", name: "New Zealand Dollar vs US Dollar" },
        { symbol: "USDCAD", name: "US Dollar vs Canadian Dollar" },
        { symbol: "USDCHF", name: "US Dollar vs Swiss Franc" },
        { symbol: "USDJPY", name: "US Dollar vs Japanese Yen" },
      ],
    },
    {
      label: "Cruces Menores",
      instruments: [
        { symbol: "AUDCAD", name: "Australian Dollar vs Canadian Dollar" },
        { symbol: "AUDCHF", name: "Australian Dollar vs Swiss Franc" },
        { symbol: "AUDJPY", name: "Australian Dollar vs Japanese Yen" },
        { symbol: "AUDNZD", name: "Australian Dollar vs New Zealand Dollar" },
        { symbol: "CADCHF", name: "Canadian Dollar vs Swiss Franc" },
        { symbol: "CADJPY", name: "Canadian Dollar vs Japanese Yen" },
        { symbol: "CHFJPY", name: "Swiss Franc vs Japanese Yen" },
        { symbol: "EURAUD", name: "Euro vs Australian Dollar" },
        { symbol: "EURCAD", name: "Euro vs Canadian Dollar" },
        { symbol: "EURCHF", name: "Euro vs Swiss Franc" },
        { symbol: "EURGBP", name: "Euro vs Great Britain Pound" },
        { symbol: "EURJPY", name: "Euro vs Japanese Yen" },
        { symbol: "EURNZD", name: "Euro vs New Zealand Dollar" },
        { symbol: "GBPAUD", name: "Great Britain Pound vs Australian Dollar" },
        { symbol: "GBPCAD", name: "Great Britain Pound vs Canadian Dollar" },
        { symbol: "GBPCHF", name: "Great Britain Pound vs Swiss Franc" },
        { symbol: "GBPJPY", name: "Great Britain Pound vs Japanese Yen" },
        { symbol: "GBPNZD", name: "Great Britain Pound vs New Zealand Dollar" },
        { symbol: "NZDCAD", name: "New Zealand Dollar vs Canadian Dollar" },
        { symbol: "NZDCHF", name: "New Zealand Dollar vs Swiss Franc" },
        { symbol: "NZDJPY", name: "New Zealand Dollar vs Japanese Yen" },
      ],
    },
    {
      label: "Exóticos",
      instruments: [
        { symbol: "AUDDKK", name: "Australian Dollar vs Danish Krone" },
        { symbol: "AUDHUF", name: "Australian Dollar vs Hungarian Forint" },
        { symbol: "AUDNOK", name: "Australian Dollar vs Norwegian Krone" },
        { symbol: "AUDSEK", name: "Australian Dollar to Swedish Krona" },
        { symbol: "AUDSGD", name: "Australian Dollar vs Singapore Dollar" },
        { symbol: "AUDZAR", name: "Australian Dollar African Rand" },
        { symbol: "CADDKK", name: "Canadian Dollar vs Danish Krone" },
        { symbol: "CADMXN", name: "Canadian Dollar vs Mexican Peso" },
        { symbol: "CADNOK", name: "Canadian Dollar vs Norwegian Krone" },
        { symbol: "CADSEK", name: "Canadian Dollar vs Swedish Krona" },
        { symbol: "CADSGD", name: "Canadian Dollar vs Singapore Dollar" },
        { symbol: "CHFDKK", name: "Swiss Franc vs Danish Krone" },
        { symbol: "CHFHUF", name: "Swiss Franc vs Hungarian Forint" },
        { symbol: "CHFNOK", name: "Swiss Franc vs Norwegian Krone" },
        { symbol: "CHFPLN", name: "Swiss Franc vs Polish Zloty" },
        { symbol: "CHFSEK", name: "Swiss Franc to Swedish Krona" },
        { symbol: "CHFSGD", name: "Swiss Franc vs Singapore Dollar" },
        { symbol: "CHFZAR", name: "Swiss Franc vs South African Rand" },
        { symbol: "CNHJPY", name: "Chinese Yuan vs Japanese Yen" },
        { symbol: "DKKNOK", name: "Danish Krone vs Norwegian Krone" },
        { symbol: "DKKSEK", name: "Danish Krone vs Swedish Krona" },
        { symbol: "EURCNH", name: "Euro vs Chinese Yuan" },
        { symbol: "EURCZK", name: "Euro vs Czech Koruna" },
        { symbol: "EURDKK", name: "Euro vs Danish Krone" },
        { symbol: "EURHKD", name: "Euro vs Hong Kong Dollar" },
        { symbol: "EURHUF", name: "Euro vs Hungarian Forint" },
        { symbol: "EURILS", name: "Euro vs Israeli Shekel" },
        { symbol: "EURMXN", name: "Euro vs Mexican Peso" },
        { symbol: "EURNOK", name: "Euro vs Norwegian Krone" },
        { symbol: "EURPLN", name: "Euro vs Polish Zloty" },
        { symbol: "EURSEK", name: "Euro vs Swedish Krona" },
        { symbol: "EURSGD", name: "Euro vs Singapore Dollar" },
        { symbol: "EURTRY", name: "Euro vs Turkish Lira" },
        { symbol: "EURZAR", name: "Euro vs South African Rand" },
        { symbol: "GBPCZK", name: "Great Britain Pound vs Czech Koruna" },
        { symbol: "GBPDKK", name: "Great Britain Pound vs Danish Krone" },
        { symbol: "GBPHKD", name: "Great Britain Pound vs Hong Kong Dollar" },
        { symbol: "GBPHUF", name: "Great Britain Pound vs Hungarian Forint" },
        { symbol: "GBPMXN", name: "Great Britain Pound vs Mexican Peso" },
        { symbol: "GBPNOK", name: "Great Britain Pound vs Norwegian Krone" },
        { symbol: "GBPPLN", name: "Great Britain Pound vs Polish Zloty" },
        { symbol: "GBPSEK", name: "Great Britain Pound vs Swedish Krona" },
        { symbol: "GBPSGD", name: "Great Britain Pound vs Singapore Dollar" },
        { symbol: "GBPTRY", name: "Great Britain Pound vs Turkish Lira" },
        { symbol: "GBPZAR", name: "Great Britain Pound vs South African Rand" },
        { symbol: "HKDJPY", name: "Hong Kong Dollar vs Japanese Yen" },
        { symbol: "MXNJPY", name: "Mexican Peso vs Japanese Yen" },
        { symbol: "NOKJPY", name: "Norwegian Krone vs Japanese Yen" },
        { symbol: "NOKSEK", name: "Norwegian Krone vs Swedish Krona" },
        { symbol: "NZDDKK", name: "New Zealand Dollar vs Danish Krone" },
        { symbol: "NZDHUF", name: "New Zealand Dollar vs Hungarian Forint" },
        { symbol: "NZDNOK", name: "New Zealand Dollar vs Norwegian Krone" },
        { symbol: "NZDSEK", name: "New Zealand Dollar vs Swedish Krona" },
        { symbol: "NZDSGD", name: "New Zealand Dollar vs Singapore Dollar" },
        { symbol: "SEKJPY", name: "Swedish Krona vs Japanese Yen" },
        { symbol: "SGDHKD", name: "Singapore Dollar vs Hong Kong Dollar" },
        { symbol: "SGDJPY", name: "Singapore Dollar vs Japanese Yen" },
        { symbol: "TRYJPY", name: "Turkish Lira vs Japanese Yen" },
        { symbol: "USDCNH", name: "US Dollar vs Chinese Yuan" },
        { symbol: "USDCZK", name: "US Dollar vs Czech Koruna" },
        { symbol: "USDDKK", name: "US Dollar vs Danish Krone" },
        { symbol: "USDHKD", name: "US Dollar vs Hong Kong Dollar" },
        { symbol: "USDHUF", name: "US Dollar vs Hungarian Forint" },
        { symbol: "USDILS", name: "US Dollar vs Israeli Shekel" },
        { symbol: "USDMXN", name: "US Dollar vs Mexican Peso" },
        { symbol: "USDNOK", name: "US Dollar vs Norwegian Krone" },
        { symbol: "USDPLN", name: "US Dollar vs Polish Zloty" },
        { symbol: "USDSEK", name: "US Dollar vs Swedish Krona" },
        { symbol: "USDSGD", name: "US Dollar vs Singapore Dollar" },
        { symbol: "USDTHB", name: "US Dollar vs Thai Baht" },
        { symbol: "USDTRY", name: "US Dollar vs Turkish Lira" },
        { symbol: "USDZAR", name: "US Dollar vs South African Rand" },
        { symbol: "ZARJPY", name: "South African Rand vs Japanese Yen" },
      ],
    },
  ],
};

export default function EsForexPage() {
  return <MarketPageTemplate data={data} />;
}
