"use client";

import MarketPageTemplate, { type MarketData } from "@/components/markets/MarketPageTemplate";

const data: MarketData = {
  name: "Crypto",
  tag: "CRYPTO",
  iconName: "bitcoin",
  accentColor: "#00BAB3",
  accentRgb: "0,186,179",
  description:
    "132 cryptocurrency instruments including major coins, altcoins, and crypto cross pairs. Trade crypto CFDs with transparent commission pricing on both RAW and STD accounts.",
  conditions: [
    { label: "Commission (vs USD)", raw: "0.004%",       std: "0.0025%" },
    { label: "Max Leverage",        raw: "1:10",          std: "1:10" },
    { label: "Execution",           raw: "Book A · NDD",  std: "Book A · NDD" },
  ],
  groups: [
    {
      label: "Major Crypto vs USD",
      instruments: [
        { symbol: "BTCUSD", name: "Bitcoin vs US Dollar" },
        { symbol: "ETHUSD", name: "Ethereum vs US Dollar" },
        { symbol: "SOLUSD", name: "Solana vs US Dollar" },
        { symbol: "BCHUSD", name: "Bitcoin Cash vs US Dollar" },
        { symbol: "XRPUSD", name: "Ripple vs US Dollar" },
        { symbol: "LTCUSD", name: "Litecoin vs US Dollar" },
        { symbol: "BNBUSD", name: "Binance Coin vs US Dollar" },
        { symbol: "DOGUSD", name: "Dogecoin vs US Dollar" },
        { symbol: "ADAUSD", name: "Cardano vs US Dollar" },
        { symbol: "SHBUSD", name: "SHIBA vs US Dollar" },
        { symbol: "AVAUSD", name: "Avalanche vs US Dollar" },
        { symbol: "TRXUSD", name: "TRON vs US Dollar" },
        { symbol: "DOTUSD", name: "Polkadot vs US Dollar" },
        { symbol: "LNKUSD", name: "Chainlink vs US Dollar" },
        { symbol: "NERUSD", name: "NEAR Protocol vs US Dollar" },
        { symbol: "UNIUSD", name: "Uniswap vs US Dollar" },
        { symbol: "XLMUSD", name: "Stellar Lumens vs US Dollar" },
        { symbol: "ALGUSD", name: "Algorand vs US Dollar" },
        { symbol: "TONUSD", name: "Toncoin vs US Dollar" },
        { symbol: "CAKUSD", name: "PancakeSwap vs US Dollar" },
        { symbol: "ETCUSD", name: "Ethereum Classic vs US Dollar" },
        { symbol: "TRUUSD", name: "Trump Coin vs US Dollar" },
        { symbol: "MLNUSD", name: "Melania Coin vs US Dollar" },
        { symbol: "FETUSD", name: "Fetch.AI vs US Dollar" },
        { symbol: "ICPUSD", name: "Internet Computer vs US Dollar" },
        { symbol: "AAVUSD", name: "AAVE vs US Dollar" },
      ],
    },
    {
      label: "Altcoins vs USD",
      instruments: [
        { symbol: "ALIUSD", name: "MyNeighborAlice vs USD" },
        { symbol: "ANKUSD", name: "Ankr vs USD" },
        { symbol: "APEUSD", name: "ApeCoin vs USD" },
        { symbol: "APTUSD", name: "Aptos vs USD" },
        { symbol: "ARWUSD", name: "Arweave vs USD" },
        { symbol: "ATMUSD", name: "Cosmos vs USD" },
        { symbol: "AXSUSD", name: "Axie Infinity vs USD" },
        { symbol: "BARUSD", name: "Hedera vs USD" },
        { symbol: "BATUSD", name: "Basic Attention Token vs USD" },
        { symbol: "CELUSD", name: "Celer Network vs USD" },
        { symbol: "CEOUSD", name: "Celo vs USD" },
        { symbol: "CHRUSD", name: "Chromia vs USD" },
        { symbol: "CHZUSD", name: "Chiliz vs USD" },
        { symbol: "CNEUSD", name: "C98 vs USD" },
        { symbol: "COMUSD", name: "Compound vs USD" },
        { symbol: "COTUSD", name: "COTI vs USD" },
        { symbol: "CRVUSD", name: "Curve vs USD" },
        { symbol: "CTSUSD", name: "Cartesi vs USD" },
        { symbol: "DSHUSD", name: "DASH vs USD" },
        { symbol: "DYDUSD", name: "dYdX vs USD" },
        { symbol: "EGLUSD", name: "Elrond vs USD" },
        { symbol: "ENJUSD", name: "Enjin Coin vs USD" },
        { symbol: "FILUSD", name: "Filecoin vs USD" },
        { symbol: "FLWUSD", name: "FLOW vs USD" },
        { symbol: "GALUSD", name: "GALA vs USD" },
        { symbol: "GMTUSD", name: "STEPN vs USD" },
        { symbol: "GRTUSD", name: "The Graph vs USD" },
        { symbol: "IMXUSD", name: "Immutable X vs USD" },
        { symbol: "INCUSD", name: "1inch vs USD" },
        { symbol: "IOSUSD", name: "IOST vs USD" },
        { symbol: "IOTUSD", name: "IOTA vs USD" },
        { symbol: "KAVUSD", name: "Kava vs USD" },
        { symbol: "KNCUSD", name: "Kyber vs USD" },
        { symbol: "KSMUSD", name: "Kusama vs USD" },
        { symbol: "LPTUSD", name: "Livepeer vs USD" },
        { symbol: "MANUSD", name: "Decentraland vs USD" },
        { symbol: "NEOUSD", name: "NEO vs USD" },
        { symbol: "ONEUSD", name: "Harmony vs USD" },
        { symbol: "ONTUSD", name: "Ontology vs USD" },
        { symbol: "PEPUSD", name: "ConstitutionDAO vs USD" },
        { symbol: "QTMUSD", name: "Qtum vs USD" },
        { symbol: "RSRUSD", name: "Reserve Rights vs USD" },
        { symbol: "RVNUSD", name: "Ravencoin vs USD" },
        { symbol: "SANUSD", name: "The Sandbox vs USD" },
        { symbol: "SKLUSD", name: "SKALE Network vs USD" },
        { symbol: "SNXUSD", name: "Synthetix vs USD" },
        { symbol: "STOUSD", name: "Storj vs USD" },
        { symbol: "SUSUSD", name: "SushiSwap vs USD" },
        { symbol: "TETUSD", name: "Theta vs USD" },
        { symbol: "VECUSD", name: "VeChain vs USD" },
        { symbol: "WOOUSD", name: "WOO Network vs USD" },
        { symbol: "XMRUSD", name: "Monero vs USD" },
        { symbol: "XTZUSD", name: "Tezos vs USD" },
        { symbol: "YFIUSD", name: "Yearn Finance vs USD" },
        { symbol: "ZECUSD", name: "ZCash vs USD" },
        { symbol: "ZENUSD", name: "Horizen vs USD" },
        { symbol: "ZILUSD", name: "Zilliqa vs USD" },
        { symbol: "ZRXUSD", name: "0x Protocol vs USD" },
      ],
    },
    {
      label: "vs Fiat Currencies",
      instruments: [
        { symbol: "BTCEUR",  name: "Bitcoin vs Euro" },
        { symbol: "BTCGBP",  name: "Bitcoin vs British Pound" },
        { symbol: "BTCJPY",  name: "Bitcoin vs Japanese Yen" },
        { symbol: "BTCCHF",  name: "Bitcoin vs Swiss Franc" },
        { symbol: "BTCAUD",  name: "Bitcoin vs Australian Dollar" },
        { symbol: "BTCNZD",  name: "Bitcoin vs New Zealand Dollar" },
        { symbol: "BTCCAD",  name: "Bitcoin vs Canadian Dollar" },
        { symbol: "BCHEUR",  name: "Bitcoin Cash vs Euro" },
        { symbol: "BCHGBP",  name: "Bitcoin Cash vs British Pound" },
        { symbol: "BCHJPY",  name: "Bitcoin Cash vs Japanese Yen" },
        { symbol: "BCHAUD",  name: "Bitcoin Cash vs Australian Dollar" },
        { symbol: "BCHCAD",  name: "Bitcoin Cash vs Canadian Dollar" },
        { symbol: "BCHNZD",  name: "Bitcoin Cash vs New Zealand Dollar" },
        { symbol: "ETHEUR",  name: "Ethereum vs Euro" },
        { symbol: "ETHGBP",  name: "Ethereum vs British Pound" },
        { symbol: "ETHJPY",  name: "Ethereum vs Japanese Yen" },
        { symbol: "ETHAUD",  name: "Ethereum vs Australian Dollar" },
        { symbol: "ETHCAD",  name: "Ethereum vs Canadian Dollar" },
        { symbol: "ETHNZD",  name: "Ethereum vs New Zealand Dollar" },
        { symbol: "LTCEUR",  name: "Litecoin vs Euro" },
        { symbol: "LTCGBP",  name: "Litecoin vs British Pound" },
        { symbol: "LTCJPY",  name: "Litecoin vs Japanese Yen" },
        { symbol: "LTCAUD",  name: "Litecoin vs Australian Dollar" },
        { symbol: "LTCCAD",  name: "Litecoin vs Canadian Dollar" },
        { symbol: "LTCNZD",  name: "Litecoin vs New Zealand Dollar" },
        { symbol: "XRPEUR",  name: "Ripple vs Euro" },
        { symbol: "BNBEUR",  name: "Binance Coin vs Euro" },
        { symbol: "BNBGBP",  name: "Binance Coin vs British Pound" },
        { symbol: "BNBJPY",  name: "Binance Coin vs Japanese Yen" },
        { symbol: "BNBAUD",  name: "Binance Coin vs Australian Dollar" },
        { symbol: "BNBCAD",  name: "Binance Coin vs Canadian Dollar" },
        { symbol: "BNBNZD",  name: "Binance Coin vs New Zealand Dollar" },
      ],
    },
    {
      label: "Cross-Crypto Pairs",
      instruments: [
        { symbol: "BTCBCH", name: "Bitcoin vs Bitcoin Cash" },
        { symbol: "BTCETH", name: "Bitcoin vs Ethereum" },
        { symbol: "BTCLTC", name: "Bitcoin vs Litecoin" },
        { symbol: "BCHBTC", name: "Bitcoin Cash vs Bitcoin" },
        { symbol: "BCHETH", name: "Bitcoin Cash vs Ethereum" },
        { symbol: "BCHLTC", name: "Bitcoin Cash vs Litecoin" },
        { symbol: "ETHBTC", name: "Ethereum vs Bitcoin" },
        { symbol: "ETHBCH", name: "Ethereum vs Bitcoin Cash" },
        { symbol: "ETHLTC", name: "Ethereum vs Litecoin" },
        { symbol: "LTCBTC", name: "Litecoin vs Bitcoin" },
        { symbol: "LTCBCH", name: "Litecoin vs Bitcoin Cash" },
        { symbol: "LTCETH", name: "Litecoin vs Ethereum" },
        { symbol: "BNBBTC", name: "Binance Coin vs Bitcoin" },
        { symbol: "BNBBCH", name: "Binance Coin vs Bitcoin Cash" },
        { symbol: "BNBETH", name: "Binance Coin vs Ethereum" },
        { symbol: "BNBLTC", name: "Binance Coin vs Litecoin" },
      ],
    },
  ],
};

export default function CryptoPage() {
  return <MarketPageTemplate data={data} />;
}
